Commit AES OCL1.2 Completed Conversion (Error)
The AES OpenCL 1.2 version has been adapted to use a main file and the common benchmarking libraries.

There are serious issues with the CMake files that make building files that reference these common libraries impossible.

Example Error:
main.cc:(.text.startup+0x111): undefined reference to `CommandLineOption::Parse(int, char const**)'
main.cc:(.text.startup+0x120): undefined reference to `CommandLineOption::GetArgumentValue(char const*)'
main.cc:(.text.startup+0x13c): undefined reference to `CommandLineOption::Help(std::ostream*)'
main.cc:(.text.startup+0x164): undefined reference to `CommandLineOption::GetArgumentValue(char const*)'

This indicates that the libraries are not being built first and ld cannot link against them.

The CMake files need to be changed to build common first OR build the libraries from the context of each benchmark.

Because of these CMake issues, I modified the common files to use relative path includes versus absolute project paths.  A version of the common libraries can be dropped in from Develop to restore the absolute includes.  These modifications were required to let the project compile successfully.

Signed-off-by: Carter McCardwell <carter@mccardwell.net>